### ISSUE TITLE
Write project requirement

### ISSUE THREAD

**Issue by azizramdan** [azizramdan/bearmentor-upperwear#1]
UpperWear is an online store that sells tops.

Inspirations: https://livehaf.com/

Features:
- Home page
  - Hero section
  - Best seller products
  - Products by category
  
 - Products catalogue, https://livehaf.com/collections/atasan
   - Images
   - Name
   - Price
   - Search form
  
- Product page, https://livehaf.com/collections/atasan/products/boxy-ease-tee-black
  - Images
  - Name
  - Price
  - Color variants, link to product
  - Size variant
  - Description
  - Size chart
  - Add to cart form: quantity input & add to cart button

- Shopping cart page
  - Product items to buy 
    - Image
    - Title
    - Size
    - Quantity, decrease/increase
    - Remove button
   - Total price
  - Link to checkout page

- Checkout page, https://livehaf.com/checkouts/cn/Z2NwLWFzaWEtc291dGhlYXN0MTowMUowM0s0MzRKMU40MlhCRVlHSFRBNkRSRg
  - Items section
    - Image, name, size, quantity, total price
    - Grand total
   - Customer detail (email or login button)
   - Delivery detail
   - Payment method

**Comment by mhaidarhanif** [comment]
All good. No problem.

**Comment by mhaidarhanif** [comment]
Later, link to Figma. Or can be in the README.
